/**
 * Webpack Plugin to Generate View Registry
 * Automatically creates viewRegistry.js with all views for lazy loading
 * 
 * @author OneLaravel Team
 * @since 2025-12-29
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export class ViewRegistryPlugin {
    constructor(options = {}) {
        // Use process.cwd() to default to the project root, making this plugin portable
        this.viewsDir = options.viewsDir || path.resolve(process.cwd(), 'resources/js/views');
        this.outputFile = options.outputFile || path.resolve(process.cwd(), 'resources/js/.generated/config/viewRegistry.js');
        this.preloadViews = options.preloadViews || [];
    }

    apply(compiler) {
        compiler.hooks.beforeCompile.tapAsync('ViewRegistryPlugin', (params, callback) => {
            this.generateViewRegistry();
            callback();
        });
    }

    generateViewRegistry() {
        const views = this.scanViews(this.viewsDir);
        const content = this.generateContent(views);
        
        // Ensure directory exists
        const dir = path.dirname(this.outputFile);
        if (!fs.existsSync(dir)) {
            fs.mkdirSync(dir, { recursive: true });
        }
        
        fs.writeFileSync(this.outputFile, content, 'utf8');
        console.log(`✅ Generated view registry with ${views.length} views`);
    }

    scanViews(dir, basePath = '') {
        const views = [];
        const files = fs.readdirSync(dir);

        files.forEach(file => {
            const fullPath = path.join(dir, file);
            const stat = fs.statSync(fullPath);

            if (stat.isDirectory()) {
                views.push(...this.scanViews(fullPath, path.join(basePath, file)));
            } else if (file.endsWith('.js')) {
                const fileName = file.replace('.js', '');
                const relativePath = path.join(basePath, file);
                
                // Convert filename to view path
                // WebPagesHome.js -> web.pages.home
                const viewPath = fileName
                    .replace(/([A-Z])/g, '.$1')
                    .toLowerCase()
                    .replace(/^\./, '');

                views.push({
                    viewPath,
                    fileName,
                    relativePath: relativePath.replace(/\\/g, '/'),
                });
            }
        });

        return views;
    }

    generateContent(views) {
        const imports = views.map(view => {
            return `    '${view.viewPath}': () => import(/* webpackChunkName: "view.${view.viewPath}" */ '../views/${view.relativePath}'),`;
        }).join('\n');

        const preloadList = this.preloadViews.map(v => `    '${v}',`).join('\n');

        return `/**
 * Auto-generated View Registry
 * DO NOT EDIT MANUALLY - Generated by ViewRegistryPlugin
 * 
 * @module config/viewRegistry
 * @generated ${new Date().toISOString()}
 */

/**
 * View registry with dynamic imports
 * Maps view paths to webpack dynamic import functions
 * 
 * @type {Object<string, () => Promise<any>>}
 */
export const viewRegistry = {
${imports}
};

/**
 * Views to preload for better initial performance
 */
export const preloadViews = [
${preloadList}
];

/**
 * Total registered views
 */
export const totalViews = ${views.length};

export default viewRegistry;
`;
    }
}

export default ViewRegistryPlugin;
